export const SIGNUP= '/auth/signup'
export const SIGNIN= '/auth/signin'
export const DASHBOARD= '/dashboard'
export const RECOVER_PASSWORD= '/auth/recover-password'
export const RESET_PASSWORD= '/auth/reset-password'
