it('Signed in user can create log', () => {
  cy.visit('http://localhost:3000/auth/signin')
  cy.get('input[name="email"]').click().type('test@mail.com')
  cy.get('input[name="password"]').click().type('testing1234')
  cy.get('button[type="submit"]').click()
  cy.url().should('eq', 'http://localhost:3000/dashboard')
  cy.visit('http://localhost:3000/logs/create')
  cy.get('select').select('test')
  cy.get('input[name="startTime"]').click().type('09:00:00')
  cy.get('input[name="endTime"]').click().type('05:00:00')
  cy.get('input[name="totalBreakDuration"]').click().type('30')
  cy.get('input[name="distance"]').click().type('15')
  cy.get('input[name="billingRate"]').click().type('75.00')
  cy.get('input[name="activitiesPerformed"]')
    .click()
    .type('General maintenance')
  cy.get('input[name="resourcesUsed"]').click().type('Chrome tube')
  cy.get('button[type="submit"]').click()
  cy.url().should('eq', 'http://localhost:3000/logs/:id')
  cy.contains('Jon Doe')
  cy.contains('09:00')
  cy.contains('17:00')
  cy.contains('30')
  cy.contains('15')
  cy.contains('General maintenance')
  cy.contains('Chrome tube')
})
